/*
 * BoldSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: support@boldsign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boldsign.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.lang.reflect.Field;
import java.net.URI;
import java.lang.reflect.Method;

import com.boldsign.JSON;
import com.boldsign.ApiException;

/**
 * CheckboxValidationSettings
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class CheckboxValidationSettings {
  /**
   * Gets or Sets validationType
   */
  @JsonAdapter(ValidationTypeEnum.Adapter.class)
  public enum ValidationTypeEnum {
    MINIMUM("Minimum"),
    
    MAXIMUM("Maximum"),
    
    ABSOLUTE("Absolute"),
    
    RANGE("Range");

    private String value;

    ValidationTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ValidationTypeEnum fromValue(String value) {
      for (ValidationTypeEnum b : ValidationTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ValidationTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ValidationTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ValidationTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ValidationTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ValidationTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_VALIDATION_TYPE = "validationType";
  @SerializedName(SERIALIZED_NAME_VALIDATION_TYPE)
  private ValidationTypeEnum validationType;

  public static final String SERIALIZED_NAME_MIN_SELECTION = "minSelection";
  @SerializedName(SERIALIZED_NAME_MIN_SELECTION)
  private Integer minSelection;

  public static final String SERIALIZED_NAME_MAX_SELECTION = "maxSelection";
  @SerializedName(SERIALIZED_NAME_MAX_SELECTION)
  private Integer maxSelection;

  public CheckboxValidationSettings() {
  }

  public CheckboxValidationSettings validationType(ValidationTypeEnum validationType) {
    this.validationType = validationType;
    return this;
  }

  /**
   * Get validationType
   * @return validationType
   */
  @javax.annotation.Nullable
  public ValidationTypeEnum getValidationType() {
    return validationType;
  }

  public void setValidationType(ValidationTypeEnum validationType) {
    this.validationType = validationType;
  }


  public CheckboxValidationSettings minSelection(Integer minSelection) {
    this.minSelection = minSelection;
    return this;
  }

  /**
   * Get minSelection
   * @return minSelection
   */
  @javax.annotation.Nullable
  public Integer getMinSelection() {
    return minSelection;
  }

  public void setMinSelection(Integer minSelection) {
    this.minSelection = minSelection;
  }


  public CheckboxValidationSettings maxSelection(Integer maxSelection) {
    this.maxSelection = maxSelection;
    return this;
  }

  /**
   * Get maxSelection
   * @return maxSelection
   */
  @javax.annotation.Nullable
  public Integer getMaxSelection() {
    return maxSelection;
  }

  public void setMaxSelection(Integer maxSelection) {
    this.maxSelection = maxSelection;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckboxValidationSettings checkboxValidationSettings = (CheckboxValidationSettings) o;
    return Objects.equals(this.validationType, checkboxValidationSettings.validationType) &&
        Objects.equals(this.minSelection, checkboxValidationSettings.minSelection) &&
        Objects.equals(this.maxSelection, checkboxValidationSettings.maxSelection);
  }

  @Override
  public int hashCode() {
    return Objects.hash(validationType, minSelection, maxSelection);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckboxValidationSettings {\n");
    sb.append("    validationType: ").append(toIndentedString(validationType)).append("\n");
    sb.append("    minSelection: ").append(toIndentedString(minSelection)).append("\n");
    sb.append("    maxSelection: ").append(toIndentedString(maxSelection)).append("\n");
    sb.append("}");
    return sb.toString();
  }
  public Map<String, Object> createFormData() throws ApiException {
    Map<String, Object> map = new HashMap<>();
    boolean fileTypeFound = false;
    try {
    if (validationType != null) {
        if (isFileTypeOrListOfFiles(validationType)) {
            fileTypeFound = true;
        }

        if (validationType.getClass().equals(java.io.File.class) ||
            validationType.getClass().equals(Integer.class) ||
            validationType.getClass().equals(String.class) ||
            validationType.getClass().equals(java.net.URI.class)||
            validationType.getClass().isEnum()) {
            map.put("validationType", validationType);
        } else if (isListOfFile(validationType)) {
            for(int i = 0; i< getListSize(validationType); i++) {
                map.put("validationType", validationType);
            }
        }
        else {
          map.put("validationType", JSON.serialize(validationType));
        }
    }
    if (minSelection != null) {
        if (isFileTypeOrListOfFiles(minSelection)) {
            fileTypeFound = true;
        }

        if (minSelection.getClass().equals(java.io.File.class) ||
            minSelection.getClass().equals(Integer.class) ||
            minSelection.getClass().equals(String.class) ||
            minSelection.getClass().equals(java.net.URI.class)||
            minSelection.getClass().isEnum()) {
            map.put("minSelection", minSelection);
        } else if (isListOfFile(minSelection)) {
            for(int i = 0; i< getListSize(minSelection); i++) {
                map.put("minSelection", minSelection);
            }
        }
        else {
          map.put("minSelection", JSON.serialize(minSelection));
        }
    }
    if (maxSelection != null) {
        if (isFileTypeOrListOfFiles(maxSelection)) {
            fileTypeFound = true;
        }

        if (maxSelection.getClass().equals(java.io.File.class) ||
            maxSelection.getClass().equals(Integer.class) ||
            maxSelection.getClass().equals(String.class) ||
            maxSelection.getClass().equals(java.net.URI.class)||
            maxSelection.getClass().isEnum()) {
            map.put("maxSelection", maxSelection);
        } else if (isListOfFile(maxSelection)) {
            for(int i = 0; i< getListSize(maxSelection); i++) {
                map.put("maxSelection", maxSelection);
            }
        }
        else {
          map.put("maxSelection", JSON.serialize(maxSelection));
        }
    }
    } catch (Exception e) {
        throw new ApiException(e);
    }
    return fileTypeFound ? map : new HashMap<>();
  }

  private boolean isFileTypeOrListOfFiles(Object obj) throws Exception {
    return obj.getClass().equals(java.io.File.class) || isListOfFile(obj);
  }

  private boolean isListOfFile(Object obj) throws Exception {
      return obj instanceof java.util.List && !isListEmpty(obj) && getFromList(obj, 0) instanceof java.io.File;
  }

  private boolean isListEmpty(Object obj) throws Exception {
    return (boolean) Class.forName(java.util.List.class.getName()).getMethod("isEmpty").invoke(obj);
  }

  private Object getFromList(Object obj, int index) throws Exception {
    return Class.forName(java.util.List.class.getName()).getMethod("get", int.class).invoke(obj, index);
  }

  private int getListSize(Object obj) throws Exception {
    return (int) Class.forName(java.util.List.class.getName()).getMethod("size").invoke(obj);
  }


  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("validationType");
    openapiFields.add("minSelection");
    openapiFields.add("maxSelection");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CheckboxValidationSettings
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CheckboxValidationSettings.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CheckboxValidationSettings is not found in the empty JSON string", CheckboxValidationSettings.openapiRequiredFields.toString()));
        }
      }
	  //Ignored additional properties from response json. 
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("validationType") != null && !jsonObj.get("validationType").isJsonNull()) && !jsonObj.get("validationType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `validationType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("validationType").toString()));
      }
      // validate the optional field `validationType`
      if (jsonObj.get("validationType") != null && !jsonObj.get("validationType").isJsonNull()) {
        ValidationTypeEnum.validateJsonElement(jsonObj.get("validationType"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CheckboxValidationSettings.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CheckboxValidationSettings' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CheckboxValidationSettings> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CheckboxValidationSettings.class));

       return (TypeAdapter<T>) new TypeAdapter<CheckboxValidationSettings>() {
           @Override
           public void write(JsonWriter out, CheckboxValidationSettings value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CheckboxValidationSettings read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CheckboxValidationSettings given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CheckboxValidationSettings
   * @throws IOException if the JSON string is invalid with respect to CheckboxValidationSettings
   */
  public static CheckboxValidationSettings fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CheckboxValidationSettings.class);
  }

  /**
   * Convert an instance of CheckboxValidationSettings to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

