/*
 * BoldSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: support@boldsign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boldsign.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.lang.reflect.Field;
import java.net.URI;

import com.boldsign.JSON;
import com.boldsign.ApiException;

/**
 * EmbeddedTemplatePreview
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class EmbeddedTemplatePreview {
  public static final String SERIALIZED_NAME_TEMPLATE_URL = "templateUrl";
  @SerializedName(SERIALIZED_NAME_TEMPLATE_URL)
  private URI templateUrl;

  public EmbeddedTemplatePreview() {
  }

  public EmbeddedTemplatePreview templateUrl(URI templateUrl) {
    this.templateUrl = templateUrl;
    return this;
  }

  /**
   * Get templateUrl
   * @return templateUrl
   */
  @javax.annotation.Nullable
  public URI getTemplateUrl() {
    return templateUrl;
  }

  public void setTemplateUrl(URI templateUrl) {
    this.templateUrl = templateUrl;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmbeddedTemplatePreview embeddedTemplatePreview = (EmbeddedTemplatePreview) o;
    return Objects.equals(this.templateUrl, embeddedTemplatePreview.templateUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(templateUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmbeddedTemplatePreview {\n");
    sb.append("    templateUrl: ").append(toIndentedString(templateUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }
  public Map<String, Object> createFormData() throws ApiException {
    Map<String, Object> map = new HashMap<>();
    boolean fileTypeFound = false;
    try {
    if (templateUrl != null) {
        if (isFileTypeOrListOfFiles(templateUrl)) {
            fileTypeFound = true;
        }

        if (templateUrl.getClass().equals(java.io.File.class) ||
            templateUrl.getClass().equals(Integer.class) ||
            templateUrl.getClass().equals(String.class) ||
            templateUrl.getClass().equals(java.net.URI.class)||
            templateUrl.getClass().isEnum()) {
            map.put("templateUrl", templateUrl);
        } else if (isListOfFile(templateUrl)) {
            for(int i = 0; i< getListSize(templateUrl); i++) {
                map.put("templateUrl", templateUrl);
            }
        }
        else {
          map.put("templateUrl", JSON.serialize(templateUrl));
        }
    }
    } catch (Exception e) {
        throw new ApiException(e);
    }
    return fileTypeFound ? map : new HashMap<>();
  }

  private boolean isFileTypeOrListOfFiles(Object obj) throws Exception {
    return obj.getClass().equals(java.io.File.class) || isListOfFile(obj);
  }

  private boolean isListOfFile(Object obj) throws Exception {
      return obj instanceof java.util.List && !isListEmpty(obj) && getFromList(obj, 0) instanceof java.io.File;
  }

  private boolean isListEmpty(Object obj) throws Exception {
    return (boolean) Class.forName(java.util.List.class.getName()).getMethod("isEmpty").invoke(obj);
  }

  private Object getFromList(Object obj, int index) throws Exception {
    return Class.forName(java.util.List.class.getName()).getMethod("get", int.class).invoke(obj, index);
  }

  private int getListSize(Object obj) throws Exception {
    return (int) Class.forName(java.util.List.class.getName()).getMethod("size").invoke(obj);
  }


  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("templateUrl");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EmbeddedTemplatePreview
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EmbeddedTemplatePreview.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EmbeddedTemplatePreview is not found in the empty JSON string", EmbeddedTemplatePreview.openapiRequiredFields.toString()));
        }
      }
	  //Ignored additional properties from response json. 
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("templateUrl") != null && !jsonObj.get("templateUrl").isJsonNull()) && !jsonObj.get("templateUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `templateUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("templateUrl").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EmbeddedTemplatePreview.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EmbeddedTemplatePreview' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EmbeddedTemplatePreview> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EmbeddedTemplatePreview.class));

       return (TypeAdapter<T>) new TypeAdapter<EmbeddedTemplatePreview>() {
           @Override
           public void write(JsonWriter out, EmbeddedTemplatePreview value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EmbeddedTemplatePreview read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EmbeddedTemplatePreview given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EmbeddedTemplatePreview
   * @throws IOException if the JSON string is invalid with respect to EmbeddedTemplatePreview
   */
  public static EmbeddedTemplatePreview fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EmbeddedTemplatePreview.class);
  }

  /**
   * Convert an instance of EmbeddedTemplatePreview to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

