/*
 * BoldSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: support@boldsign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boldsign.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.lang.reflect.Field;
import java.net.URI;
import java.lang.reflect.Method;

import com.boldsign.JSON;
import com.boldsign.ApiException;

/**
 * EmbeddedCustomFieldCreated
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class EmbeddedCustomFieldCreated {
  public static final String SERIALIZED_NAME_CREATE_URL = "createUrl";
  @SerializedName(SERIALIZED_NAME_CREATE_URL)
  private URI createUrl;

  public EmbeddedCustomFieldCreated() {
  }

  public EmbeddedCustomFieldCreated createUrl(URI createUrl) {
    this.createUrl = createUrl;
    return this;
  }

  /**
   * Get createUrl
   * @return createUrl
   */
  @javax.annotation.Nullable
  public URI getCreateUrl() {
    return createUrl;
  }

  public void setCreateUrl(URI createUrl) {
    this.createUrl = createUrl;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmbeddedCustomFieldCreated embeddedCustomFieldCreated = (EmbeddedCustomFieldCreated) o;
    return Objects.equals(this.createUrl, embeddedCustomFieldCreated.createUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmbeddedCustomFieldCreated {\n");
    sb.append("    createUrl: ").append(toIndentedString(createUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }
  public Map<String, Object> createFormData() throws ApiException {
    Map<String, Object> map = new HashMap<>();
    boolean fileTypeFound = false;
    try {
    if (createUrl != null) {
        if (isFileTypeOrListOfFiles(createUrl)) {
            fileTypeFound = true;
        }

        if (createUrl.getClass().equals(java.io.File.class) ||
            createUrl.getClass().equals(Integer.class) ||
            createUrl.getClass().equals(String.class) ||
            createUrl.getClass().equals(java.net.URI.class)||
            createUrl.getClass().isEnum()) {
            map.put("createUrl", createUrl);
        } else if (isListOfFile(createUrl)) {
            for(int i = 0; i< getListSize(createUrl); i++) {
                map.put("createUrl", createUrl);
            }
        }
        else {
          map.put("createUrl", JSON.serialize(createUrl));
        }
    }
    } catch (Exception e) {
        throw new ApiException(e);
    }
    return fileTypeFound ? map : new HashMap<>();
  }

  private boolean isFileTypeOrListOfFiles(Object obj) throws Exception {
    return obj.getClass().equals(java.io.File.class) || isListOfFile(obj);
  }

  private boolean isListOfFile(Object obj) throws Exception {
      return obj instanceof java.util.List && !isListEmpty(obj) && getFromList(obj, 0) instanceof java.io.File;
  }

  private boolean isListEmpty(Object obj) throws Exception {
    return (boolean) Class.forName(java.util.List.class.getName()).getMethod("isEmpty").invoke(obj);
  }

  private Object getFromList(Object obj, int index) throws Exception {
    return Class.forName(java.util.List.class.getName()).getMethod("get", int.class).invoke(obj, index);
  }

  private int getListSize(Object obj) throws Exception {
    return (int) Class.forName(java.util.List.class.getName()).getMethod("size").invoke(obj);
  }


  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("createUrl");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EmbeddedCustomFieldCreated
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EmbeddedCustomFieldCreated.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EmbeddedCustomFieldCreated is not found in the empty JSON string", EmbeddedCustomFieldCreated.openapiRequiredFields.toString()));
        }
      }
	  //Ignored additional properties from response json. 
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("createUrl") != null && !jsonObj.get("createUrl").isJsonNull()) && !jsonObj.get("createUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `createUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("createUrl").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EmbeddedCustomFieldCreated.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EmbeddedCustomFieldCreated' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EmbeddedCustomFieldCreated> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EmbeddedCustomFieldCreated.class));

       return (TypeAdapter<T>) new TypeAdapter<EmbeddedCustomFieldCreated>() {
           @Override
           public void write(JsonWriter out, EmbeddedCustomFieldCreated value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EmbeddedCustomFieldCreated read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EmbeddedCustomFieldCreated given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EmbeddedCustomFieldCreated
   * @throws IOException if the JSON string is invalid with respect to EmbeddedCustomFieldCreated
   */
  public static EmbeddedCustomFieldCreated fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EmbeddedCustomFieldCreated.class);
  }

  /**
   * Convert an instance of EmbeddedCustomFieldCreated to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

