/*
 * BoldSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: support@boldsign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boldsign.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.lang.reflect.Field;
import java.net.URI;

import com.boldsign.JSON;
import com.boldsign.ApiException;

/**
 * RecipientNotificationSettings
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class RecipientNotificationSettings {
  public static final String SERIALIZED_NAME_SIGNATURE_REQUEST = "signatureRequest";
  @SerializedName(SERIALIZED_NAME_SIGNATURE_REQUEST)
  private Boolean signatureRequest = true;

  public static final String SERIALIZED_NAME_DECLINED = "declined";
  @SerializedName(SERIALIZED_NAME_DECLINED)
  private Boolean declined = true;

  public static final String SERIALIZED_NAME_REVOKED = "revoked";
  @SerializedName(SERIALIZED_NAME_REVOKED)
  private Boolean revoked = true;

  public static final String SERIALIZED_NAME_SIGNED = "signed";
  @SerializedName(SERIALIZED_NAME_SIGNED)
  private Boolean signed = true;

  public static final String SERIALIZED_NAME_COMPLETED = "completed";
  @SerializedName(SERIALIZED_NAME_COMPLETED)
  private Boolean completed = true;

  public static final String SERIALIZED_NAME_EXPIRED = "expired";
  @SerializedName(SERIALIZED_NAME_EXPIRED)
  private Boolean expired = true;

  public static final String SERIALIZED_NAME_REASSIGNED = "reassigned";
  @SerializedName(SERIALIZED_NAME_REASSIGNED)
  private Boolean reassigned = true;

  public static final String SERIALIZED_NAME_DELETED = "deleted";
  @SerializedName(SERIALIZED_NAME_DELETED)
  private Boolean deleted = true;

  public static final String SERIALIZED_NAME_REMINDERS = "reminders";
  @SerializedName(SERIALIZED_NAME_REMINDERS)
  private Boolean reminders = true;

  public static final String SERIALIZED_NAME_EDIT_RECIPIENT = "editRecipient";
  @SerializedName(SERIALIZED_NAME_EDIT_RECIPIENT)
  private Boolean editRecipient = true;

  public static final String SERIALIZED_NAME_EDIT_DOCUMENT = "editDocument";
  @SerializedName(SERIALIZED_NAME_EDIT_DOCUMENT)
  private Boolean editDocument = true;

  public static final String SERIALIZED_NAME_VIEWED = "viewed";
  @SerializedName(SERIALIZED_NAME_VIEWED)
  private Boolean viewed;

  public RecipientNotificationSettings() {
  }

  public RecipientNotificationSettings signatureRequest(Boolean signatureRequest) {
    this.signatureRequest = signatureRequest;
    return this;
  }

  /**
   * Get signatureRequest
   * @return signatureRequest
   */
  @javax.annotation.Nullable
  public Boolean getSignatureRequest() {
    return signatureRequest;
  }

  public void setSignatureRequest(Boolean signatureRequest) {
    this.signatureRequest = signatureRequest;
  }


  public RecipientNotificationSettings declined(Boolean declined) {
    this.declined = declined;
    return this;
  }

  /**
   * Get declined
   * @return declined
   */
  @javax.annotation.Nullable
  public Boolean getDeclined() {
    return declined;
  }

  public void setDeclined(Boolean declined) {
    this.declined = declined;
  }


  public RecipientNotificationSettings revoked(Boolean revoked) {
    this.revoked = revoked;
    return this;
  }

  /**
   * Get revoked
   * @return revoked
   */
  @javax.annotation.Nullable
  public Boolean getRevoked() {
    return revoked;
  }

  public void setRevoked(Boolean revoked) {
    this.revoked = revoked;
  }


  public RecipientNotificationSettings signed(Boolean signed) {
    this.signed = signed;
    return this;
  }

  /**
   * Get signed
   * @return signed
   */
  @javax.annotation.Nullable
  public Boolean getSigned() {
    return signed;
  }

  public void setSigned(Boolean signed) {
    this.signed = signed;
  }


  public RecipientNotificationSettings completed(Boolean completed) {
    this.completed = completed;
    return this;
  }

  /**
   * Get completed
   * @return completed
   */
  @javax.annotation.Nullable
  public Boolean getCompleted() {
    return completed;
  }

  public void setCompleted(Boolean completed) {
    this.completed = completed;
  }


  public RecipientNotificationSettings expired(Boolean expired) {
    this.expired = expired;
    return this;
  }

  /**
   * Get expired
   * @return expired
   */
  @javax.annotation.Nullable
  public Boolean getExpired() {
    return expired;
  }

  public void setExpired(Boolean expired) {
    this.expired = expired;
  }


  public RecipientNotificationSettings reassigned(Boolean reassigned) {
    this.reassigned = reassigned;
    return this;
  }

  /**
   * Get reassigned
   * @return reassigned
   */
  @javax.annotation.Nullable
  public Boolean getReassigned() {
    return reassigned;
  }

  public void setReassigned(Boolean reassigned) {
    this.reassigned = reassigned;
  }


  public RecipientNotificationSettings deleted(Boolean deleted) {
    this.deleted = deleted;
    return this;
  }

  /**
   * Get deleted
   * @return deleted
   */
  @javax.annotation.Nullable
  public Boolean getDeleted() {
    return deleted;
  }

  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }


  public RecipientNotificationSettings reminders(Boolean reminders) {
    this.reminders = reminders;
    return this;
  }

  /**
   * Get reminders
   * @return reminders
   */
  @javax.annotation.Nullable
  public Boolean getReminders() {
    return reminders;
  }

  public void setReminders(Boolean reminders) {
    this.reminders = reminders;
  }


  public RecipientNotificationSettings editRecipient(Boolean editRecipient) {
    this.editRecipient = editRecipient;
    return this;
  }

  /**
   * Get editRecipient
   * @return editRecipient
   */
  @javax.annotation.Nullable
  public Boolean getEditRecipient() {
    return editRecipient;
  }

  public void setEditRecipient(Boolean editRecipient) {
    this.editRecipient = editRecipient;
  }


  public RecipientNotificationSettings editDocument(Boolean editDocument) {
    this.editDocument = editDocument;
    return this;
  }

  /**
   * Get editDocument
   * @return editDocument
   */
  @javax.annotation.Nullable
  public Boolean getEditDocument() {
    return editDocument;
  }

  public void setEditDocument(Boolean editDocument) {
    this.editDocument = editDocument;
  }


  public RecipientNotificationSettings viewed(Boolean viewed) {
    this.viewed = viewed;
    return this;
  }

  /**
   * Get viewed
   * @return viewed
   */
  @javax.annotation.Nullable
  public Boolean getViewed() {
    return viewed;
  }

  public void setViewed(Boolean viewed) {
    this.viewed = viewed;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecipientNotificationSettings recipientNotificationSettings = (RecipientNotificationSettings) o;
    return Objects.equals(this.signatureRequest, recipientNotificationSettings.signatureRequest) &&
        Objects.equals(this.declined, recipientNotificationSettings.declined) &&
        Objects.equals(this.revoked, recipientNotificationSettings.revoked) &&
        Objects.equals(this.signed, recipientNotificationSettings.signed) &&
        Objects.equals(this.completed, recipientNotificationSettings.completed) &&
        Objects.equals(this.expired, recipientNotificationSettings.expired) &&
        Objects.equals(this.reassigned, recipientNotificationSettings.reassigned) &&
        Objects.equals(this.deleted, recipientNotificationSettings.deleted) &&
        Objects.equals(this.reminders, recipientNotificationSettings.reminders) &&
        Objects.equals(this.editRecipient, recipientNotificationSettings.editRecipient) &&
        Objects.equals(this.editDocument, recipientNotificationSettings.editDocument) &&
        Objects.equals(this.viewed, recipientNotificationSettings.viewed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signatureRequest, declined, revoked, signed, completed, expired, reassigned, deleted, reminders, editRecipient, editDocument, viewed);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecipientNotificationSettings {\n");
    sb.append("    signatureRequest: ").append(toIndentedString(signatureRequest)).append("\n");
    sb.append("    declined: ").append(toIndentedString(declined)).append("\n");
    sb.append("    revoked: ").append(toIndentedString(revoked)).append("\n");
    sb.append("    signed: ").append(toIndentedString(signed)).append("\n");
    sb.append("    completed: ").append(toIndentedString(completed)).append("\n");
    sb.append("    expired: ").append(toIndentedString(expired)).append("\n");
    sb.append("    reassigned: ").append(toIndentedString(reassigned)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    reminders: ").append(toIndentedString(reminders)).append("\n");
    sb.append("    editRecipient: ").append(toIndentedString(editRecipient)).append("\n");
    sb.append("    editDocument: ").append(toIndentedString(editDocument)).append("\n");
    sb.append("    viewed: ").append(toIndentedString(viewed)).append("\n");
    sb.append("}");
    return sb.toString();
  }
  public Map<String, Object> createFormData() throws ApiException {
    Map<String, Object> map = new HashMap<>();
    boolean fileTypeFound = false;
    try {
    if (signatureRequest != null) {
        if (isFileTypeOrListOfFiles(signatureRequest)) {
            fileTypeFound = true;
        }

        if (signatureRequest.getClass().equals(java.io.File.class) ||
            signatureRequest.getClass().equals(Integer.class) ||
            signatureRequest.getClass().equals(String.class) ||
            signatureRequest.getClass().isEnum()) {
            map.put("signatureRequest", signatureRequest);
        } else if (isListOfFile(signatureRequest)) {
            for(int i = 0; i< getListSize(signatureRequest); i++) {
                map.put("signatureRequest", signatureRequest);
            }
        }
        else {
          map.put("signatureRequest", signatureRequest);
        }
    }
    if (declined != null) {
        if (isFileTypeOrListOfFiles(declined)) {
            fileTypeFound = true;
        }

        if (declined.getClass().equals(java.io.File.class) ||
            declined.getClass().equals(Integer.class) ||
            declined.getClass().equals(String.class) ||
            declined.getClass().isEnum()) {
            map.put("declined", declined);
        } else if (isListOfFile(declined)) {
            for(int i = 0; i< getListSize(declined); i++) {
                map.put("declined", declined);
            }
        }
        else {
          map.put("declined", declined);
        }
    }
    if (revoked != null) {
        if (isFileTypeOrListOfFiles(revoked)) {
            fileTypeFound = true;
        }

        if (revoked.getClass().equals(java.io.File.class) ||
            revoked.getClass().equals(Integer.class) ||
            revoked.getClass().equals(String.class) ||
            revoked.getClass().isEnum()) {
            map.put("revoked", revoked);
        } else if (isListOfFile(revoked)) {
            for(int i = 0; i< getListSize(revoked); i++) {
                map.put("revoked", revoked);
            }
        }
        else {
          map.put("revoked", revoked);
        }
    }
    if (signed != null) {
        if (isFileTypeOrListOfFiles(signed)) {
            fileTypeFound = true;
        }

        if (signed.getClass().equals(java.io.File.class) ||
            signed.getClass().equals(Integer.class) ||
            signed.getClass().equals(String.class) ||
            signed.getClass().isEnum()) {
            map.put("signed", signed);
        } else if (isListOfFile(signed)) {
            for(int i = 0; i< getListSize(signed); i++) {
                map.put("signed", signed);
            }
        }
        else {
          map.put("signed", signed);
        }
    }
    if (completed != null) {
        if (isFileTypeOrListOfFiles(completed)) {
            fileTypeFound = true;
        }

        if (completed.getClass().equals(java.io.File.class) ||
            completed.getClass().equals(Integer.class) ||
            completed.getClass().equals(String.class) ||
            completed.getClass().isEnum()) {
            map.put("completed", completed);
        } else if (isListOfFile(completed)) {
            for(int i = 0; i< getListSize(completed); i++) {
                map.put("completed", completed);
            }
        }
        else {
          map.put("completed", completed);
        }
    }
    if (expired != null) {
        if (isFileTypeOrListOfFiles(expired)) {
            fileTypeFound = true;
        }

        if (expired.getClass().equals(java.io.File.class) ||
            expired.getClass().equals(Integer.class) ||
            expired.getClass().equals(String.class) ||
            expired.getClass().isEnum()) {
            map.put("expired", expired);
        } else if (isListOfFile(expired)) {
            for(int i = 0; i< getListSize(expired); i++) {
                map.put("expired", expired);
            }
        }
        else {
          map.put("expired", expired);
        }
    }
    if (reassigned != null) {
        if (isFileTypeOrListOfFiles(reassigned)) {
            fileTypeFound = true;
        }

        if (reassigned.getClass().equals(java.io.File.class) ||
            reassigned.getClass().equals(Integer.class) ||
            reassigned.getClass().equals(String.class) ||
            reassigned.getClass().isEnum()) {
            map.put("reassigned", reassigned);
        } else if (isListOfFile(reassigned)) {
            for(int i = 0; i< getListSize(reassigned); i++) {
                map.put("reassigned", reassigned);
            }
        }
        else {
          map.put("reassigned", reassigned);
        }
    }
    if (deleted != null) {
        if (isFileTypeOrListOfFiles(deleted)) {
            fileTypeFound = true;
        }

        if (deleted.getClass().equals(java.io.File.class) ||
            deleted.getClass().equals(Integer.class) ||
            deleted.getClass().equals(String.class) ||
            deleted.getClass().isEnum()) {
            map.put("deleted", deleted);
        } else if (isListOfFile(deleted)) {
            for(int i = 0; i< getListSize(deleted); i++) {
                map.put("deleted", deleted);
            }
        }
        else {
          map.put("deleted", deleted);
        }
    }
    if (reminders != null) {
        if (isFileTypeOrListOfFiles(reminders)) {
            fileTypeFound = true;
        }

        if (reminders.getClass().equals(java.io.File.class) ||
            reminders.getClass().equals(Integer.class) ||
            reminders.getClass().equals(String.class) ||
            reminders.getClass().isEnum()) {
            map.put("reminders", reminders);
        } else if (isListOfFile(reminders)) {
            for(int i = 0; i< getListSize(reminders); i++) {
                map.put("reminders", reminders);
            }
        }
        else {
          map.put("reminders", reminders);
        }
    }
    if (editRecipient != null) {
        if (isFileTypeOrListOfFiles(editRecipient)) {
            fileTypeFound = true;
        }

        if (editRecipient.getClass().equals(java.io.File.class) ||
            editRecipient.getClass().equals(Integer.class) ||
            editRecipient.getClass().equals(String.class) ||
            editRecipient.getClass().isEnum()) {
            map.put("editRecipient", editRecipient);
        } else if (isListOfFile(editRecipient)) {
            for(int i = 0; i< getListSize(editRecipient); i++) {
                map.put("editRecipient", editRecipient);
            }
        }
        else {
          map.put("editRecipient", editRecipient);
        }
    }
    if (editDocument != null) {
        if (isFileTypeOrListOfFiles(editDocument)) {
            fileTypeFound = true;
        }

        if (editDocument.getClass().equals(java.io.File.class) ||
            editDocument.getClass().equals(Integer.class) ||
            editDocument.getClass().equals(String.class) ||
            editDocument.getClass().isEnum()) {
            map.put("editDocument", editDocument);
        } else if (isListOfFile(editDocument)) {
            for(int i = 0; i< getListSize(editDocument); i++) {
                map.put("editDocument", editDocument);
            }
        }
        else {
          map.put("editDocument", editDocument);
        }
    }
    if (viewed != null) {
        if (isFileTypeOrListOfFiles(viewed)) {
            fileTypeFound = true;
        }

        if (viewed.getClass().equals(java.io.File.class) ||
            viewed.getClass().equals(Integer.class) ||
            viewed.getClass().equals(String.class) ||
            viewed.getClass().isEnum()) {
            map.put("viewed", viewed);
        } else if (isListOfFile(viewed)) {
            for(int i = 0; i< getListSize(viewed); i++) {
                map.put("viewed", viewed);
            }
        }
        else {
          map.put("viewed", viewed);
        }
    }
    } catch (Exception e) {
        throw new ApiException(e);
    }
    return fileTypeFound ? map : new HashMap<>();
  }

  private boolean isFileTypeOrListOfFiles(Object obj) throws Exception {
    return obj.getClass().equals(java.io.File.class) || isListOfFile(obj);
  }

  private boolean isListOfFile(Object obj) throws Exception {
      return obj instanceof java.util.List && !isListEmpty(obj) && getFromList(obj, 0) instanceof java.io.File;
  }

  private boolean isListEmpty(Object obj) throws Exception {
    return (boolean) Class.forName(java.util.List.class.getName()).getMethod("isEmpty").invoke(obj);
  }

  private Object getFromList(Object obj, int index) throws Exception {
    return Class.forName(java.util.List.class.getName()).getMethod("get", int.class).invoke(obj, index);
  }

  private int getListSize(Object obj) throws Exception {
    return (int) Class.forName(java.util.List.class.getName()).getMethod("size").invoke(obj);
  }


  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("signatureRequest");
    openapiFields.add("declined");
    openapiFields.add("revoked");
    openapiFields.add("signed");
    openapiFields.add("completed");
    openapiFields.add("expired");
    openapiFields.add("reassigned");
    openapiFields.add("deleted");
    openapiFields.add("reminders");
    openapiFields.add("editRecipient");
    openapiFields.add("editDocument");
    openapiFields.add("viewed");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RecipientNotificationSettings
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RecipientNotificationSettings.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RecipientNotificationSettings is not found in the empty JSON string", RecipientNotificationSettings.openapiRequiredFields.toString()));
        }
      }
	  //Ignored additional properties from response json. 
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RecipientNotificationSettings.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RecipientNotificationSettings' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RecipientNotificationSettings> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RecipientNotificationSettings.class));

       return (TypeAdapter<T>) new TypeAdapter<RecipientNotificationSettings>() {
           @Override
           public void write(JsonWriter out, RecipientNotificationSettings value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RecipientNotificationSettings read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RecipientNotificationSettings given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RecipientNotificationSettings
   * @throws IOException if the JSON string is invalid with respect to RecipientNotificationSettings
   */
  public static RecipientNotificationSettings fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RecipientNotificationSettings.class);
  }

  /**
   * Convert an instance of RecipientNotificationSettings to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

