/*
 * BoldSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: support@boldsign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boldsign.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.lang.reflect.Field;
import java.net.URI;

import com.boldsign.JSON;
import com.boldsign.ApiException;

/**
 * ReminderSettings
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class ReminderSettings {
  public static final String SERIALIZED_NAME_ENABLE_AUTO_REMINDER = "enableAutoReminder";
  @SerializedName(SERIALIZED_NAME_ENABLE_AUTO_REMINDER)
  private Boolean enableAutoReminder = false;

  public static final String SERIALIZED_NAME_REMINDER_DAYS = "reminderDays";
  @SerializedName(SERIALIZED_NAME_REMINDER_DAYS)
  private Integer reminderDays = 3;

  public static final String SERIALIZED_NAME_REMINDER_COUNT = "reminderCount";
  @SerializedName(SERIALIZED_NAME_REMINDER_COUNT)
  private Integer reminderCount = 3;

  public ReminderSettings() {
  }

  public ReminderSettings enableAutoReminder(Boolean enableAutoReminder) {
    this.enableAutoReminder = enableAutoReminder;
    return this;
  }

  /**
   * Get enableAutoReminder
   * @return enableAutoReminder
   */
  @javax.annotation.Nullable
  public Boolean getEnableAutoReminder() {
    return enableAutoReminder;
  }

  public void setEnableAutoReminder(Boolean enableAutoReminder) {
    this.enableAutoReminder = enableAutoReminder;
  }


  public ReminderSettings reminderDays(Integer reminderDays) {
    this.reminderDays = reminderDays;
    return this;
  }

  /**
   * Get reminderDays
   * @return reminderDays
   */
  @javax.annotation.Nullable
  public Integer getReminderDays() {
    return reminderDays;
  }

  public void setReminderDays(Integer reminderDays) {
    this.reminderDays = reminderDays;
  }


  public ReminderSettings reminderCount(Integer reminderCount) {
    this.reminderCount = reminderCount;
    return this;
  }

  /**
   * Get reminderCount
   * @return reminderCount
   */
  @javax.annotation.Nullable
  public Integer getReminderCount() {
    return reminderCount;
  }

  public void setReminderCount(Integer reminderCount) {
    this.reminderCount = reminderCount;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReminderSettings reminderSettings = (ReminderSettings) o;
    return Objects.equals(this.enableAutoReminder, reminderSettings.enableAutoReminder) &&
        Objects.equals(this.reminderDays, reminderSettings.reminderDays) &&
        Objects.equals(this.reminderCount, reminderSettings.reminderCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enableAutoReminder, reminderDays, reminderCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReminderSettings {\n");
    sb.append("    enableAutoReminder: ").append(toIndentedString(enableAutoReminder)).append("\n");
    sb.append("    reminderDays: ").append(toIndentedString(reminderDays)).append("\n");
    sb.append("    reminderCount: ").append(toIndentedString(reminderCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }
  public Map<String, Object> createFormData() throws ApiException {
    Map<String, Object> map = new HashMap<>();
    boolean fileTypeFound = false;
    try {
    if (enableAutoReminder != null) {
        if (isFileTypeOrListOfFiles(enableAutoReminder)) {
            fileTypeFound = true;
        }

        if (enableAutoReminder.getClass().equals(java.io.File.class) ||
            enableAutoReminder.getClass().equals(Integer.class) ||
            enableAutoReminder.getClass().equals(String.class) ||
            enableAutoReminder.getClass().equals(java.net.URI.class)||
            enableAutoReminder.getClass().isEnum()) {
            map.put("enableAutoReminder", enableAutoReminder);
        } else if (isListOfFile(enableAutoReminder)) {
            for(int i = 0; i< getListSize(enableAutoReminder); i++) {
                map.put("enableAutoReminder", enableAutoReminder);
            }
        }
        else {
          map.put("enableAutoReminder", JSON.serialize(enableAutoReminder));
        }
    }
    if (reminderDays != null) {
        if (isFileTypeOrListOfFiles(reminderDays)) {
            fileTypeFound = true;
        }

        if (reminderDays.getClass().equals(java.io.File.class) ||
            reminderDays.getClass().equals(Integer.class) ||
            reminderDays.getClass().equals(String.class) ||
            reminderDays.getClass().equals(java.net.URI.class)||
            reminderDays.getClass().isEnum()) {
            map.put("reminderDays", reminderDays);
        } else if (isListOfFile(reminderDays)) {
            for(int i = 0; i< getListSize(reminderDays); i++) {
                map.put("reminderDays", reminderDays);
            }
        }
        else {
          map.put("reminderDays", JSON.serialize(reminderDays));
        }
    }
    if (reminderCount != null) {
        if (isFileTypeOrListOfFiles(reminderCount)) {
            fileTypeFound = true;
        }

        if (reminderCount.getClass().equals(java.io.File.class) ||
            reminderCount.getClass().equals(Integer.class) ||
            reminderCount.getClass().equals(String.class) ||
            reminderCount.getClass().equals(java.net.URI.class)||
            reminderCount.getClass().isEnum()) {
            map.put("reminderCount", reminderCount);
        } else if (isListOfFile(reminderCount)) {
            for(int i = 0; i< getListSize(reminderCount); i++) {
                map.put("reminderCount", reminderCount);
            }
        }
        else {
          map.put("reminderCount", JSON.serialize(reminderCount));
        }
    }
    } catch (Exception e) {
        throw new ApiException(e);
    }
    return fileTypeFound ? map : new HashMap<>();
  }

  private boolean isFileTypeOrListOfFiles(Object obj) throws Exception {
    return obj.getClass().equals(java.io.File.class) || isListOfFile(obj);
  }

  private boolean isListOfFile(Object obj) throws Exception {
      return obj instanceof java.util.List && !isListEmpty(obj) && getFromList(obj, 0) instanceof java.io.File;
  }

  private boolean isListEmpty(Object obj) throws Exception {
    return (boolean) Class.forName(java.util.List.class.getName()).getMethod("isEmpty").invoke(obj);
  }

  private Object getFromList(Object obj, int index) throws Exception {
    return Class.forName(java.util.List.class.getName()).getMethod("get", int.class).invoke(obj, index);
  }

  private int getListSize(Object obj) throws Exception {
    return (int) Class.forName(java.util.List.class.getName()).getMethod("size").invoke(obj);
  }


  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("enableAutoReminder");
    openapiFields.add("reminderDays");
    openapiFields.add("reminderCount");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ReminderSettings
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ReminderSettings.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ReminderSettings is not found in the empty JSON string", ReminderSettings.openapiRequiredFields.toString()));
        }
      }
	  //Ignored additional properties from response json. 
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ReminderSettings.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ReminderSettings' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ReminderSettings> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ReminderSettings.class));

       return (TypeAdapter<T>) new TypeAdapter<ReminderSettings>() {
           @Override
           public void write(JsonWriter out, ReminderSettings value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ReminderSettings read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ReminderSettings given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ReminderSettings
   * @throws IOException if the JSON string is invalid with respect to ReminderSettings
   */
  public static ReminderSettings fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ReminderSettings.class);
  }

  /**
   * Convert an instance of ReminderSettings to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

