/*
 * BoldSign API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Contact: support@boldsign.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.boldsign.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.lang.reflect.Field;
import java.net.URI;
import java.lang.reflect.Method;

import com.boldsign.JSON;
import com.boldsign.ApiException;

/**
 * TemplateShareErrorResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class TemplateShareErrorResponse {
  public static final String SERIALIZED_NAME_TEAMS = "teams";
  @SerializedName(SERIALIZED_NAME_TEAMS)
  private List<String> teams;

  public static final String SERIALIZED_NAME_TEMPLATE_ID = "templateId";
  @SerializedName(SERIALIZED_NAME_TEMPLATE_ID)
  private String templateId;

  public static final String SERIALIZED_NAME_ERROR_TYPE = "errorType";
  @SerializedName(SERIALIZED_NAME_ERROR_TYPE)
  private String errorType;

  public static final String SERIALIZED_NAME_ERROR = "error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  private String error;

  public TemplateShareErrorResponse() {
  }

  public TemplateShareErrorResponse teams(List<String> teams) {
    this.teams = teams;
    return this;
  }

  public TemplateShareErrorResponse addTeamsItem(String teamsItem) {
    if (this.teams == null) {
      this.teams = new ArrayList<>();
    }
    this.teams.add(teamsItem);
    return this;
  }

  /**
   * Get teams
   * @return teams
   */
  @javax.annotation.Nullable
  public List<String> getTeams() {
    return teams;
  }

  public void setTeams(List<String> teams) {
    this.teams = teams;
  }


  public TemplateShareErrorResponse templateId(String templateId) {
    this.templateId = templateId;
    return this;
  }

  /**
   * Get templateId
   * @return templateId
   */
  @javax.annotation.Nullable
  public String getTemplateId() {
    return templateId;
  }

  public void setTemplateId(String templateId) {
    this.templateId = templateId;
  }


  public TemplateShareErrorResponse errorType(String errorType) {
    this.errorType = errorType;
    return this;
  }

  /**
   * Get errorType
   * @return errorType
   */
  @javax.annotation.Nullable
  public String getErrorType() {
    return errorType;
  }

  public void setErrorType(String errorType) {
    this.errorType = errorType;
  }


  public TemplateShareErrorResponse error(String error) {
    this.error = error;
    return this;
  }

  /**
   * Get error
   * @return error
   */
  @javax.annotation.Nullable
  public String getError() {
    return error;
  }

  public void setError(String error) {
    this.error = error;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplateShareErrorResponse templateShareErrorResponse = (TemplateShareErrorResponse) o;
    return Objects.equals(this.teams, templateShareErrorResponse.teams) &&
        Objects.equals(this.templateId, templateShareErrorResponse.templateId) &&
        Objects.equals(this.errorType, templateShareErrorResponse.errorType) &&
        Objects.equals(this.error, templateShareErrorResponse.error);
  }

  @Override
  public int hashCode() {
    return Objects.hash(teams, templateId, errorType, error);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateShareErrorResponse {\n");
    sb.append("    teams: ").append(toIndentedString(teams)).append("\n");
    sb.append("    templateId: ").append(toIndentedString(templateId)).append("\n");
    sb.append("    errorType: ").append(toIndentedString(errorType)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }
  public Map<String, Object> createFormData() throws ApiException {
    Map<String, Object> map = new HashMap<>();
    boolean fileTypeFound = false;
    try {
    if (teams != null) {
        if (isFileTypeOrListOfFiles(teams)) {
            fileTypeFound = true;
        }

        if (teams.getClass().equals(java.io.File.class) ||
            teams.getClass().equals(Integer.class) ||
            teams.getClass().equals(String.class) ||
            teams.getClass().equals(java.net.URI.class)||
            teams.getClass().isEnum()) {
            map.put("teams", teams);
        } else if (isListOfFile(teams)) {
            for(int i = 0; i< getListSize(teams); i++) {
                map.put("teams", teams);
            }
        }
        else {
          List<String> objectList = new ArrayList<String>();
          for(Object item : teams) {
            if(item instanceof URI || item instanceof String || item instanceof Integer || item instanceof Enum) {
              objectList.add(item.toString());
            }
            else if (item instanceof EditDocumentFile) {
              int index = 0;
              EditDocumentFile fileItem = (EditDocumentFile) item;
              for (String field : EditDocumentFile.openapiFields) {
                String methodName = "get" + field.substring(0, 1).toUpperCase() + field.substring(1);
                Method getter = EditDocumentFile.class.getMethod(methodName);
                Object value = getter.invoke(fileItem);
                String key = "files[" + index + "]." + field;
                if (value != null){
                  if(field == "file"){
                    fileTypeFound = true;
                  }
                map.put(key, value);
                }
              }
              index++;
            }
            else {
              String objectData = JSON.serialize(item);
              objectList.add(objectData);
            }
          }
          map.put("teams", objectList);
        }
    }
    if (templateId != null) {
        if (isFileTypeOrListOfFiles(templateId)) {
            fileTypeFound = true;
        }

        if (templateId.getClass().equals(java.io.File.class) ||
            templateId.getClass().equals(Integer.class) ||
            templateId.getClass().equals(String.class) ||
            templateId.getClass().equals(java.net.URI.class)||
            templateId.getClass().isEnum()) {
            map.put("templateId", templateId);
        } else if (isListOfFile(templateId)) {
            for(int i = 0; i< getListSize(templateId); i++) {
                map.put("templateId", templateId);
            }
        }
        else {
          map.put("templateId", JSON.serialize(templateId));
        }
    }
    if (errorType != null) {
        if (isFileTypeOrListOfFiles(errorType)) {
            fileTypeFound = true;
        }

        if (errorType.getClass().equals(java.io.File.class) ||
            errorType.getClass().equals(Integer.class) ||
            errorType.getClass().equals(String.class) ||
            errorType.getClass().equals(java.net.URI.class)||
            errorType.getClass().isEnum()) {
            map.put("errorType", errorType);
        } else if (isListOfFile(errorType)) {
            for(int i = 0; i< getListSize(errorType); i++) {
                map.put("errorType", errorType);
            }
        }
        else {
          map.put("errorType", JSON.serialize(errorType));
        }
    }
    if (error != null) {
        if (isFileTypeOrListOfFiles(error)) {
            fileTypeFound = true;
        }

        if (error.getClass().equals(java.io.File.class) ||
            error.getClass().equals(Integer.class) ||
            error.getClass().equals(String.class) ||
            error.getClass().equals(java.net.URI.class)||
            error.getClass().isEnum()) {
            map.put("error", error);
        } else if (isListOfFile(error)) {
            for(int i = 0; i< getListSize(error); i++) {
                map.put("error", error);
            }
        }
        else {
          map.put("error", JSON.serialize(error));
        }
    }
    } catch (Exception e) {
        throw new ApiException(e);
    }
    return fileTypeFound ? map : new HashMap<>();
  }

  private boolean isFileTypeOrListOfFiles(Object obj) throws Exception {
    return obj.getClass().equals(java.io.File.class) || isListOfFile(obj);
  }

  private boolean isListOfFile(Object obj) throws Exception {
      return obj instanceof java.util.List && !isListEmpty(obj) && getFromList(obj, 0) instanceof java.io.File;
  }

  private boolean isListEmpty(Object obj) throws Exception {
    return (boolean) Class.forName(java.util.List.class.getName()).getMethod("isEmpty").invoke(obj);
  }

  private Object getFromList(Object obj, int index) throws Exception {
    return Class.forName(java.util.List.class.getName()).getMethod("get", int.class).invoke(obj, index);
  }

  private int getListSize(Object obj) throws Exception {
    return (int) Class.forName(java.util.List.class.getName()).getMethod("size").invoke(obj);
  }


  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("teams");
    openapiFields.add("templateId");
    openapiFields.add("errorType");
    openapiFields.add("error");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TemplateShareErrorResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TemplateShareErrorResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TemplateShareErrorResponse is not found in the empty JSON string", TemplateShareErrorResponse.openapiRequiredFields.toString()));
        }
      }
	  //Ignored additional properties from response json. 
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("teams") != null && !jsonObj.get("teams").isJsonNull() && !jsonObj.get("teams").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `teams` to be an array in the JSON string but got `%s`", jsonObj.get("teams").toString()));
      }
      if ((jsonObj.get("templateId") != null && !jsonObj.get("templateId").isJsonNull()) && !jsonObj.get("templateId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `templateId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("templateId").toString()));
      }
      if ((jsonObj.get("errorType") != null && !jsonObj.get("errorType").isJsonNull()) && !jsonObj.get("errorType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `errorType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("errorType").toString()));
      }
      if ((jsonObj.get("error") != null && !jsonObj.get("error").isJsonNull()) && !jsonObj.get("error").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `error` to be a primitive type in the JSON string but got `%s`", jsonObj.get("error").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TemplateShareErrorResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TemplateShareErrorResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TemplateShareErrorResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TemplateShareErrorResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<TemplateShareErrorResponse>() {
           @Override
           public void write(JsonWriter out, TemplateShareErrorResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TemplateShareErrorResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TemplateShareErrorResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TemplateShareErrorResponse
   * @throws IOException if the JSON string is invalid with respect to TemplateShareErrorResponse
   */
  public static TemplateShareErrorResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TemplateShareErrorResponse.class);
  }

  /**
   * Convert an instance of TemplateShareErrorResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

